### ISSUE TITLE
Issues running Example 1 on MESAS

### ISSUE THREAD

**Issue by emgrande** [charman2/mesas#1]
Dear Ciaran, 
this is Emilio, Margaret Zimmer's student, It was a pleasure meeting you over AGU. Below I'm pasting the error I am getting when trying to run Example 1, synthetic steady, on your mesas package; I get the same error for Example 2.
Thank you in advance.
Best,
Emilio

/Users/emiliogrande/.conda/envs/mesas/bin/python /Users/emiliogrande/Documents/GitHub/mesas/mesas/dev/synthetic_steady.py
Traceback (most recent call last):
  File "/Users/emiliogrande/Documents/GitHub/mesas/mesas/dev/synthetic_steady.py", line 33, in <module>
    from mesas.sas.model import Model
  File "/Users/emiliogrande/Documents/GitHub/mesas/mesas/sas/model.py", line 13, in <module>
    from f_solve import f_solve
ModuleNotFoundError: No module named 'f_solve'

Process finished with exit code 1

**Comment by charman2** [comment]
Hi Emilio - the underlying issue that caused this has been fixed in the lastest version, but the example will now break for other reasons (I've changed the way you specify the SAS function). I'll close this once I've added an example that works.

**Comment by charman2** [comment]
The new version includes working examples and documentation. Reopen this issue if you have any troubles!
